language: node_js
os: linux
dist: xenial
node_js:
  - lts/*
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    install: npm install
    before_script:
      - cp ./secrets/sample-config.json ./secrets/config.json
      - npm test
    - script: tsc -p ./tsconfig.json
    - script: COVERALLS_FLAG_NAME=test-1 make test-coveralls-1
    - script: COVERALLS_FLAG_NAME=test-2 make test-coveralls-2
notifications:
  webhooks: https://coveralls.io/webhook